name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 100
          persist-credentials: false

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@f486e936b0689690db364c7407e2182876293aa8 # v1
        with:
          args: "--no-color -qo '011'"
          annotate: warning
          
